### ISSUE TITLE
On LG NExus 5x unnecessary padding shows

### ISSUE THREAD

**Issue by nagendraK6** [mitchtabian/TabianCustomCamera#4]
I am testing ur code on LG nexus 5X. On camera preview it shows black padding (which seems unnecessary). On image capture it stretches to full screen (as expected). How can we fix the preview padding?

**Comment by nagendraK6** [comment]
@mitchtabian  Can u help me on this issue?  I am the paid member of your course.

**Comment by mitchtabian** [comment]
Can you follow in instructions for submitting an issue? https://player.vimeo.com/video/274979439
