### ISSUE TITLE
Actually its not an issue , but i wanna ask something // 

### ISSUE THREAD

**Issue by AliShujaatBhatti** [mitchtabian/TabianCustomCamera#6]
If We want to write something on Image Using An EditText Then the procedure will be the same or something differnet ? can you roughly guide me

**Comment by mitchtabian** [comment]
If would be roughly the same. You would programmatically at a TextView to the canvas and give it an id. It's the same process as everything else. Just different things happen when you touch is for example. When you touch it you'd want to open the keyboard and the capture input. 

Email me next time please.
